// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using family_hub_prototype.Data;

#nullable disable

namespace family_hub_prototype.Migrations
{
    [DbContext(typeof(FamilyHubPrototypeContext))]
    [Migration("20230412170243_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("family_hub_prototype.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskAssigneeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TaskCompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TaskDueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TaskIsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
